create database library;
use library;
create table Librarian( LibrarianID int primary key, LibrarianName varchar(20), Username varchar(20), Password varchar(16));
insert into Librarian(LibrarianID, LibrarianName , Username , Password) values (1, 'Bob', 'Bob_Smith', 'Bob@123');
insert into Librarian(LibrarianID, LibrarianName , Username , Password) values (2,'Jacob', 'Jacob A','Jacob@345'),(3,'Dora', 'Dora Bujji','Dora45@7'),(4,'Raju', 'Mighty Raju','M@dgjRaju'),(5,'Pavithra', 'Pavithra KA','Pavi$1995'),(6,'Pranaya', 'Pranaya Raj','Pranya%679*'),(7,'Hanuman', 'Hanu M@n','Hanumhdkk');
update Librarian set  LibrarianName = 'Jonny' where LibrarianID = 3;
select * from Librarian;
drop table Librarian;
create table Book(BookID int primary key , BookName varchar(50), AuthorName varchar(20), Pages int, Parts int, PublishedYear varchar(20), PublishedBy varchar(20));
insert into Book(BookID , BookName, AuthorName, Pages, Parts, PublishedYear, PublishedBy) values ( 1, 'Ponniyin Selvan', 'Kalki', 2000, 5, 1990, 'Agaram Pathipagam'),(2, 'Indru Oru Thagaval', 'Swaminathan', 1000, 20,  1995, 'Radio'),(3, 'Kambarayanam', 'Kambar', 3000, 0, 1985, 'Tamil'),(4, 'Parthiban Kanavu', 'Kalki', 2000, null, 1987, 'ABC Pathipagam');
insert into Book(BookID , BookName, AuthorName, Pages, Parts, PublishedYear, PublishedBy) values (5, 'Digital System','ABC Author',1050, 1, 2000, 'ABC Publishers'),(6, 'Data Management','Old Author',200, 1, 2010, 'Known Publishers'),(7, 'Networking','George',2500, 1, 2012, 'XYZ Publishers');
update Book set AuthorName = 'XYZ Author' where BookID = 7;
select * from Book;
drop table Book;
create table Readers (ReaderID int primary key, ReaderName varchar(20), BookID int, foreign key(BookID) references Book(BookID), Username varchar(20), Password varchar(16), Email varchar(20), ContactNumber varchar(10), Address varchar(100));
insert into Readers(ReaderID, ReaderName, BookID, Username, Password, Email, ContactNumber, Address) values ( 1, 'Smith', 2, 'Corol Smith', 'Smith@890', 'smith@gmail.com', '1234567890', 'Coimbatore'),(2, 'Chotu', 1, 'Chotta Bheem' , 'Bheem$!@3', 'chottabh@gmail.com', '8907634521','Trichy');
insert into Readers(ReaderID, ReaderName, BookID, Username, Password, Email, ContactNumber, Address) values (3, 'Jeni', 3, 'Jeni Ramesh', 'Jeni@123', 'Jeniramesh@gmail.com','1233456789','PDKT'),(4, 'Dinesh', 4, 'Dhinesh', 'Dhinesh@893j', 'Dhinesh@gmail.com','1233456898','Trichy'),(5, 'Somu', 5, 'Somesh', 'Somesh@123', 'somesh@gmail.com','6789856789','Mysore');
update Readers set ReaderName = 'sumesh' where ReaderID= 5;
select * from Readers;
drop table readers;
create table Cart(CartID int primary key, ReaderID int, foreign key(ReaderID) references Readers(ReaderID), BookID int,foreign key(BookID) references Book(BookID), BookCount int);
insert into Cart(CartID, ReaderID, BookID, BookCount) values(1, 1, 2, 2 ),(2, 2, 1, 1);
insert into Cart(CartID, ReaderID, BookID, BookCount) values(3, 3, 3, 2 ),(4, 4, 4, 3);
update cart set BookCount = 5 where CartID = 4;
select * from Cart;
drop table cart;
create table Returns(ReturnID int primary key, ReaderID int, foreign key(ReaderID) references Readers(ReaderID), BookID int, foreign key(BookID) references Book(BookID), ReturnDate date, NoOfBooks int, BookStatus varchar(50));
insert into Returns(ReturnID, ReaderID, BookID, ReturnDate, NoOfBooks, BookStatus) values(101, 1, 2, '2025-03-27', 2, 'No Damages'),(102, 2, 1, '2025-04-17', 1, 'Damaged. Need to pay penalty.');
insert into Returns(ReturnID, ReaderID, BookID, ReturnDate, NoOfBooks, BookStatus) values(103, 3, 3, '2023-04-04', 2, 'No damages'),(104, 4, 4, '2023-04-05', 3, 'Book Lost');
update returns set BookStatus = 'Lost one book' where ReturnID = 104;
select * from Returns;
drop table returns;
create table Payment( PaymentID int primary key, ReaderID int,foreign key(ReaderID) references Readers(ReaderID) , BookID int,foreign key(BookID) references Book(BookID), PaymentDate date, PaymentMode varchar(20), Amount int);
insert into Payment( PaymentID, ReaderID, BookID, PaymentDate, PaymentMode, Amount) values(1001, 2, 1, '2025-04-17', 'Online Payment', 100);
insert into Payment( PaymentID, ReaderID, BookID, PaymentDate, PaymentMode, Amount) values(1002, 4, 4, '2023-04-05', 'Cash Payment', 3000);
update payment set PaymentMode = 'Credit Card' where PaymentID= 1002;
select * from Payment;
drop table payments;
drop database library;